apiVersion: apps/v1
kind: Deployment
metadata:
  name: contact
  labels:
    app: contact
spec:
  replicas: 2
  selector:
    matchLabels:
      app: contact
  template:
    metadata:
      labels:
        app: contact
    spec:
      containers:
      - name: contact
        image: ecommerce:latest
        imagePullPolicy: Never # Added a specific tag for better version control
        ports:
        - containerPort: 80
